name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # daily 8am UTC

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Sync from LeetCode
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          leetcode-csrf-token: ${{ secrets.CSRFTOKEN }}
          destination-folder: problems
